// AUTO-GENERATED from @types/youtube. Do not edit.
// Regenerate with `pnpm generate`.

export const functionNames = [
  "addEventListener",
  "cuePlaylist",
  "cueVideoById",
  "cueVideoByUrl",
  "destroy",
  "getAvailablePlaybackRates",
  "getAvailableQualityLevels",
  "getCurrentTime",
  "getDuration",
  "getIframe",
  "getPlaybackQuality",
  "getPlaybackRate",
  "getPlayerState",
  "getPlaylist",
  "getPlaylistIndex",
  "getSphericalProperties",
  "getVideoData",
  "getVideoEmbedCode",
  "getVideoLoadedFraction",
  "getVideoUrl",
  "getVolume",
  "isMuted",
  "loadPlaylist",
  "loadVideoById",
  "loadVideoByUrl",
  "mute",
  "nextVideo",
  "pauseVideo",
  "playVideo",
  "playVideoAt",
  "previousVideo",
  "removeEventListener",
  "seekTo",
  "setLoop",
  "setPlaybackQuality",
  "setPlaybackRate",
  "setShuffle",
  "setSize",
  "setSphericalProperties",
  "setVolume",
  "stopVideo",
  "unMute"
] as const;

export type FunctionName = (typeof functionNames)[number];
